services:
  app:
    image: serversideup/php:8.4-fpm-nginx
    ports:
      - "8000:8080"
    volumes:
      - .:/var/www/html
    environment:
      - AUTORUN_LARAVEL_MIGRATION=false
      - AUTORUN_LARAVEL_STORAGE_LINK=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
